version: '3.6'

services:
  node:
    build:
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/nodejs
    command: bash -c "npm install && npm run watch"
    env_file:
      - .env
  mongodb:
    image: library/mongo:4.0.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: library/mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    volumes:
      - ./data/db:/data/db
    ports:
      - 8081:8081